spring:
  application:
    name: notes-app-graphql
  datasource:
    url: jdbc:postgresql://localhost:5432/notesgraphqlapidb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect